spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:insurtech-db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  cloud:
    aws:
      s3:
        bucket: dev-insurtech-claim-file-bucket
      region:
        static: eu-central-1
      credentials: # Specify only for local running to get access to AWS
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

  scheduler:
    auth:
      refresh-token-clean-up: "0 0 2 1/15 * *"

auth:
  jwt:
    issuer: ${JWT_ISSUER:https://insurtech.com}
    audience: ${JWT_AUDIENCE:api}
    access-token-ttl-seconds: ${ACCESS_TOKEN_TTL:900}   # 15 min
    refresh-token-ttl-days: ${REFRESH_TOKEN_TTL_DAYS:7} # 7 days
    private-key-base64: ${JWT_PRIVATE_KEY}
    public-key-base64: ${JWT_PUBLIC_KEY}
  public-paths:
    - /insurtech/v1/auth/register
    - /insurtech/v1/auth/login
    - /insurtech/v1/auth/refresh
    - /insurtech/v1/actuator/**